# GitLab CI/CD Configuration File for Automating Deployment
# This file pulls changes, installs dependencies, builds the project, and restarts the PM2 process on the server

stages: # Define the stages of the pipeline
  - deploy # Define a single deploy stage

deploy:
  stage: deploy
  only:
    - main # Adjust this to your default branch
  before_script:
    - mkdir -p ~/.ssh # Create the .ssh directory if it doesn't exist
    - chmod 700 ~/.ssh # Set permissions for .ssh directory
    - touch ~/.ssh/known_hosts # Create the known_hosts file if it doesn't exist
    - chmod 644 ~/.ssh/known_hosts # Set permissions for known_hosts file
    - ssh-keyscan -p 23 -t rsa,ed25519 -v 192.168.1.51
  script:
    - set -x # Enable debug output
    - echo "Deploying to the server..."
    - ssh -p 23 aimo@192.168.1.51 'cd /home/aimo/fe-front-end && git pull ssh main && npm install && pm2 restart 0'

# Optional Cache for npm dependencies (improves speed)
cache:
  paths:
    - node_modules/
